### ISSUE TITLE
upload limit

### ISSUE THREAD

**Issue by celevra** [devgeniem/docker-wordpress#4]
Hi,

is there a way to change the php upload Limit?

regards

**Comment by onnimonni** [comment]
In debian version of the container you can set this env: `NGINX_MAX_BODY_SIZE="10M"`.

I'm planning to add that into the alpine version as well.

**Comment by celevra** [comment]
the max body size sets also the php upload_max_filesize and post_max_size?

**Comment by onnimonni** [comment]
That's correct. It also sets them for php in here: https://github.com/devgeniem/docker-wordpress/blob/master/debian-php7.0/rootfs/etc/php/7.0/fpm/conf.d/limits.ini

**Comment by celevra** [comment]
cool, thank you!

**Comment by onnimonni** [comment]
Thanks for asking! I try to update the project readme today.
